export const copy = {
  ko: {
    appTitle: "AI 영어 교정 채팅",
    chatMode: "영어로 대화",
    askExpression: "표현 알아보기",
    inputPlaceholder: "영어로 입력해보세요",
    expressionPlaceholder: "한국어로 말하고 싶은 내용을 입력하세요",
    send: "전송",
    translate: "번역",
    listen: "듣기",
    corrected: "교정 문장",
    highlighted: "오류 표시",
    natural: "자연스러운 표현",
    explanation: "설명",
    example: "예문",
    useThisExpression: "이 표현으로 말하기",
    save: "저장",
    saved: "저장됨",
    archive: "아카이브",
    archiveEmpty: "저장된 표현이 없습니다.",
    savedItemsTab: "저장한 표현",
    sessionsTab: "대화 기록",
    sessionsEmpty: "저장된 대화 기록이 없습니다.",
    openSession: "열어보기",
    clearSessions: "대화 기록 초기화",
    freeTraining: "자유 연습",
    messagesUsed: "사용 메시지",
    resetArchive: "아카이브 초기화",
    closeArchive: "닫기",
    continuePractice: "이어서 연습하기",
    comeBackTomorrow: "내일 다시 하기",
    trainingDoneTitle: "오늘의 영어 훈련 완료 👍",
    trainingDoneBody: "내일 다시 이어서 연습해보세요",
    trainingDoneHint: "계속 연습하고 싶다면 이어서 대화할 수 있어요",
    delete: "삭제",
    reuse: "다시 쓰기",
    translating: "번역 중...",
    translation: "번역",
    translateFailed: "번역에 실패했어요. 다시 시도해 주세요.",
    dailyLimitReached:
      "오늘의 메시지 한도에 도달했어요. 내일 다시 시도해 주세요.",
    expressionHelperTitle: "💡 이렇게 말할 수 있어요",
    correctionTitle: "교정",
    noCorrectionNeeded: "수정할 필요가 없습니다.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "오늘의 영어 훈련을 완료했어요 👍",
    startNewSession: "새 대화 시작",
    endSession: "세션 종료",
    languageKorean: "한국어",
    languageEnglish: "English",
    languageSpanish: "Español",
  },
  en: {
    appTitle: "AI English Correction Chat",
    chatMode: "Chat in English",
    askExpression: "Ask expression",
    inputPlaceholder: "Try writing in English",
    expressionPlaceholder: "Type what you want to say in Korean",
    send: "Send",
    translate: "Translate",
    listen: "Listen",
    corrected: "Corrected",
    highlighted: "Highlighted mistakes",
    natural: "Natural",
    explanation: "Explanation",
    example: "Example",
    useThisExpression: "Say with this expression",
    save: "Save",
    saved: "Saved",
    archive: "Archive",
    archiveEmpty: "No saved items yet.",
    savedItemsTab: "Saved expressions",
    sessionsTab: "Conversation history",
    sessionsEmpty: "No saved conversation sessions.",
    openSession: "Open",
    clearSessions: "Clear conversation history",
    freeTraining: "Free training",
    messagesUsed: "Messages used",
    resetArchive: "Reset archive",
    closeArchive: "Close",
    continuePractice: "Continue Practice",
    comeBackTomorrow: "Come back tomorrow",
    trainingDoneTitle: "You've completed today's training 👍",
    trainingDoneBody: "Come back tomorrow to continue.",
    trainingDoneHint: "If you want, you can keep practicing now.",
    delete: "Delete",
    reuse: "Reuse",
    translating: "Translating...",
    translation: "Translation",
    translateFailed: "Translation failed. Please try again.",
    dailyLimitReached: "You reached today's message limit. Please come back tomorrow.",
    expressionHelperTitle: "💡 You can say it like this",
    correctionTitle: "Correction",
    noCorrectionNeeded: "No changes needed.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Today's practice is complete 🎯",
    startNewSession: "Start New Session",
    endSession: "End Session",
    languageKorean: "Korean",
    languageEnglish: "English",
    languageSpanish: "Spanish",
  },
  es: {
    appTitle: "Chat de correccion de ingles con IA",
    chatMode: "Hablar en ingles",
    askExpression: "Preguntar expresion",
    inputPlaceholder: "Escribe en ingles",
    expressionPlaceholder: "Escribe en coreano lo que quieres decir",
    send: "Enviar",
    translate: "Traducir",
    listen: "Escuchar",
    corrected: "Correccion",
    highlighted: "Errores marcados",
    natural: "Expresion mas natural",
    explanation: "Explicacion",
    example: "Ejemplo",
    useThisExpression: "Hablar con esta expresion",
    save: "Guardar",
    saved: "Guardado",
    archive: "Archivo",
    archiveEmpty: "No hay elementos guardados.",
    savedItemsTab: "Expresiones guardadas",
    sessionsTab: "Historial de conversaciones",
    sessionsEmpty: "No hay sesiones guardadas.",
    openSession: "Abrir",
    clearSessions: "Borrar historial",
    freeTraining: "Practica libre",
    messagesUsed: "Mensajes usados",
    resetArchive: "Reiniciar archivo",
    closeArchive: "Cerrar",
    continuePractice: "Continuar practicando",
    comeBackTomorrow: "Volver manana",
    trainingDoneTitle: "Has completado el entrenamiento de hoy 👍",
    trainingDoneBody: "Vuelve manana para continuar.",
    trainingDoneHint: "Si quieres, puedes seguir practicando ahora.",
    delete: "Eliminar",
    reuse: "Reutilizar",
    translating: "Traduciendo...",
    translation: "Traduccion",
    translateFailed: "No se pudo traducir. Intentalo de nuevo.",
    dailyLimitReached: "Llegaste al limite de mensajes de hoy. Vuelve manana.",
    expressionHelperTitle: "💡 Puedes decirlo asi",
    correctionTitle: "Correccion",
    noCorrectionNeeded: "No hace falta corregir.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Completaste la practica de hoy 🎯",
    startNewSession: "Start New Session",
    endSession: "Finalizar sesion",
    languageKorean: "Coreano",
    languageEnglish: "Ingles",
    languageSpanish: "Espanol",
  },
} as const;

export type Locale = keyof typeof copy;
export type UICopy = (typeof copy)[Locale];
